### PR TITLE
Fix ON/OFF handling on recent ThinkPad t440p BIOS

### PR DESCRIPTION
**Pull request by doudou**
This pull request fixes the ON/OFF handling on Lenovo ThinkPad t440p with recent BIOSes. See the second half of the thread in #78 for the complete background.

The general idea is that with recent BIOSes, the call to _DSM does not switch the card OFF, the transition to D3 does. An end result is that the card's identity does not change in lspci and the current state detection method in bbswitch is broken (and the card cannot be turned back ON after it is OFF). This PR implements a different mode where the card state is inferred from the ACPI-reported power state. Set use_acpi_to_detect_card_state to 1 to use this new mode.

### CODE REVIEW

**Comment by smunaut** [comment]
You might want to read what I wrote in #112 because it might be that you're not getting all the power savings you should.

**Comment by ArchangeGabriel** [comment]
@Lekensteyn Any thoughts on this patch? Maybe we could first ship it this way an tell people who want to that they can try it, and if no issue arise, either make it the default or mix it with current way of doing things (in case they are some corner cases for this new method).

**Comment by doudou** [comment]
@Lekensteyn: as @smunaut noticed, my patch does fix the corruption issue, but the card is only put in D3 and not powered off, at least on recent Lenovo firmware versions. For that, one need to put the PCIe root in D3 (which Linux does not do automatically). @smunaut has a working hack that does it.
(https://github.com/Bumblebee-Project/bbswitch/issues/112). I say a hack because it turns the PCIe root off without telling the linux driver about it ....

**Comment by Lekensteyn** [comment]
Sorry for the delay, I could not give a meaningful response before. Now I looked into the details again and your (and @smunaut) observations are correct, `_DSM` cannot be used for turning it off. See also https://github.com/Bumblebee-Project/bbswitch/issues/115#issuecomment-218622306 for an initial analysis.

`_PS3` only brings a device in D3hot state, so it is indeed not fully off (and the reported value by bbswitch is correct, it is indeed still ON). For the device to be put in fully off state (D3cold), the power resources have to be disabled (see the earlier comment for a reference to the ACPI specification).

If I remember correctly, the `pci-set_power_state` functions do correctly call `_PS3` (bbswitch should probably use `PCI_D3hot` instead of `PCI_D3cold` for normal cases). Your patch tries to make bbswitch report OFF when the device is (hopefully) in D3hot, right? I think that we need something like #112 (have yet to review that, but if the idea is to put the parent PCIe port in OFF state, I think it is a good direction).

**Comment by doudou** [comment]
Yes. This PR is obsolete now that we @smunaut found the real underlying issue.

**Pull request closed without merging**
